### PR TITLE
solve chatapp empty bug

### LINKED ISSUE #1: Bug in chatapp page
Multiple times of empty inputs can cause white screen.

### PR DESCRIPTION
**Pull request by zcemycl**

### CODE REVIEW

File: src/components/Chatapp/Chatapp.jsx [hunk 1]
```diff
@@ -36,14 +36,14 @@ const Chatapp = () => {
...
-        console.log(valueText.current.value);
-        console.log(valueUser.current.value);
-        console.log(socketRef.current.id);
-        socketRef.current.emit('my_event', {
-            body: valueText.current.value,
-            user: valueUser.current.value,
-            senderId: socketRef.current.id,
-          });
+
+        if (valueText.current.value !== "" && valueUser.current.value !== ""){
```
Comment (zcemycl) [inline src/components/Chatapp/Chatapp.jsx:40]: Avoid empty username and text message.
